version: "3.7"

services:
  php:
    image: stfc-prod-php:latest
    restart: always

  nginx:
    image: stfc-prod-nginx:latest
    restart: always
    depends_on:
      - php
    ports:
      - "8002:80"
