services:
  php:
    build:
      context: ../../
      dockerfile: devops/images/stfc_dev_php.Dockerfile

  nginx:
    build:
      context: ../images
      dockerfile: nginx.Dockerfile
    depends_on:
      - php
    ports:
      - "8002:80"
