version: "3.7"

services:
  php:
    build:
      context: ../images
      dockerfile: stfc_dev_php.Dockerfile

  nginx:
    build:
      context: ../images
      dockerfile: nginx.Dockerfile
    depends_on:
      - php
    ports:
      - "8002:80"
