version: "3.7"

services:
  php:
    build:
      context: ../../
      dockerfile: devops/images/stfc_dev_php.Dockerfile

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dev_db_stfc:/var/lib/mysql

  nginx:
    build:
      context: ../images
      dockerfile: nginx.Dockerfile
    depends_on:
      - php
    ports:
      - "8002:80"

volumes:
  dev_db_stfc: